### ISSUE TITLE
Feature suggestion: Deploy as single pod instead of daemonset

### ISSUE THREAD

**Issue by Almenon** [digitalocean/doks-debug#21]
It would be nice if there was a single pod deployment option, no point in multiple pods if I'm just planning on using this once for one pod.

**Comment by timoreimann** [comment]
👋 we might not have it mentioned in the README, but there's already https://github.com/digitalocean/doks-debug/blob/master/k8s/deployment.yaml which I hope would work for you.

**Comment by Almenon** [comment]
@timoreimann thanks!

**Comment by timoreimann** [comment]
Could probably highlight the fact that we have the deployment in the README. Fairly easy PR to pick up for anyone that would like to make a small contribution.

UPDATE: filed an issue about this.
